# Generated by Django 4.0.4 on 2022-05-12 02:30
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def populate_sections(apps, scemaeditor):
    sections = {
        "Frontpage": "All of the frontpage articles",
        "Sports": "Sports stuff and things",
        "Society": "Things people are doing and saying",
        "Business": "BIG money",
    }
    section = apps.get_model('articles', 'Section')
    for name, description in sections.items():
        single_section = section(name = name, description = description)
        single_section.save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.section')),
            ],
        ),
        migrations.RunPython(populate_sections)
    ]
