# Generated by Django 4.0.4 on 2022-05-12 00:45

from django.db import migrations, models
import django.db.models.deletion

def populate_languages(apps, scemaeditor):
    languages = {
        "EN": "English",
        "ES": "Espanol",
        "DE": "Deutsh",
        "PT": "Portugues",
    }
    language = apps.get_model('accounts', 'Language')
    for key, name in languages.items():
        single_language = language(key = key, name = name)
        single_language.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_language_customuser_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.language'),
        ),
        migrations.RunPython(populate_languages)
    ]